language: java

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11

env:
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.7
  - ECLIPSE_TARGET_PLATFORM=Eclipse-4.8
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2018-09
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2018-12
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2019-03
  - ECLIPSE_TARGET_PLATFORM=Eclipse-2019-06

install: true

script: mvn -Dtarget.platform=$ECLIPSE_TARGET_PLATFORM clean verify
